In [4]:
import numpy as np
a=np.array([[[2,3,5],[4,5,6]],[[6,7,1],[8,9,7]]])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[[2 3 5]
  [4 5 6]]

 [[6 7 1]
  [8 9 7]]]
(2, 2, 3)
3
int64


In [5]:
x = np.array([[7,2,3],[2,3,4],[5,6,9]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(x)
print(y)

[[7 2 3]
 [2 3 4]
 [5 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(x*y)

[[ 7  4  9]
 [ 8 15 24]
 [35 48 81]]


In [7]:
print(x@y)

[[ 36  48  60]
 [ 42  51  60]
 [ 92 112 132]]


In [3]:
import numpy as np
x = np.array([[7,2,3],[2,3,4],[5,6,9]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(x,y) # it is a function which will do the dot product of x and y

array([[ 36,  48,  60],
       [ 42,  51,  60],
       [ 92, 112, 132]])