In [3]:
''' numpy works with scientific calculation easily and helps in 
assistance to it'''

# it mostly works with array

import numpy as np

a= np.array([1,2,3,4,5,6])
b= np.array([1,2,3,4,5,6])

print(a)
print(b)
print(type(a))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 2  4  6  8 10 12]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]
[1. 1. 1. 1. 1. 1.]


In [10]:
# Creating 2d array

a2 =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print(a2.shape) # this line tells about the shape of array i.e.rows and column

(3, 3)


In [ ]:
print(a3.ndim)# tells dimension of array

3


In [18]:
print(a2.dtype) # tells the data type of array

int64


In [ ]:
np.arange(10)  # this creates the array from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [16]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.random.randint(1,11 , )